name:                casheServer
version:             0.1.0.0
github:              "daniilprohorov/casheServer"
license:             BSD3
author:              "Daniil Prohorov"
maintainer:          "daniilprohorov@gmail.com"
copyright:           "2021 Daniil Prohorov"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/casheServer#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- cron
- cmdargs
- servant-server
- servant-client
- http-client
- unordered-containers
- text
- time
- wai
- warp
- yaml

library:
  source-dirs: src

executables:
  casheServer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - casheServer

tests:
  casheServer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - casheServer
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
